### ISSUE TITLE
Compilation error in xcode when using 1.0.1+1

### ISSUE THREAD

**Issue by RexNexstream** [rmtmckenzie/flutter_qr_mobile_vision#142]
I had these error when try to compile iOS runner :

```
Could not find or use auto-linked library 'swiftObjectiveC'

Could not find or use auto-linked library 'swiftCoreGraphics'

Could not find or use auto-linked library 'swiftCoreFoundation'

Could not find or use auto-linked library 'swiftCompatibility50'

Could not find or use auto-linked library 'swiftDarwin'

Could not find or use auto-linked library 'swiftDispatch'

Could not find or use auto-linked library 'swiftSwiftOnoneSupport'

Could not find or use auto-linked library 'swiftCoreMedia'

Could not find or use auto-linked library 'swiftAVFoundation'

Could not find or use auto-linked library 'swiftCompatibilityDynamicReplacements'

Could not find or use auto-linked library 'swiftCoreImage'

Could not find or use auto-linked library 'swiftCoreAudio'

Could not find or use auto-linked library 'swiftUIKit'

Could not find or use auto-linked library 'swiftQuartzCore'

Could not find or use auto-linked library 'swiftos'

Could not find or use auto-linked library 'swiftCore'

Could not find or use auto-linked library 'swiftCoreMIDI'

Could not find or use auto-linked library 'swiftsimd'

Could not find or use auto-linked library 'swiftFoundation'

Could not find or use auto-linked library 'swiftMetal'


```
My app contain a notification service extension. 
It is working fine in **qr_mobile_vision: 0.3.0**
but getting error above when updated to **qr_mobile_vision:^1.0.1+1**.

**Comment by MoSamir** [comment]
Check the comments in this link , it helped building the iOS Project

https://stackoverflow.com/questions/52536380/why-linker-link-static-libraries-with-errors-ios
